version : '2'
services:
  ngtesting-mysql:
    image: registry.cn-hangzhou.aliyuncs.com/ngtesting/ngtesting-mysql:1.0.10
    environment:
      - MYSQL_ROOT_PASSWORD=P2ssw0rd
    ports:
      - "53306:3306"
    expose:
      - "53306"

  ngtesting-web:
    image: registry.cn-hangzhou.aliyuncs.com/ngtesting/ngtesting-web:1.0.10
    ports:
      - "58080:8080"
    links:
      - ngtesting-mysql
