spring:
    profiles:
      active: prod
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/, file:${sys.work.dir}, file:${sys.work.my-mind-test}
    freemarker:
      template-loader-path: classpath:/mail-template/
    datasource:
        name: mysql_ngtesting
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat
          driver-class-name: com.mysql.jdbc.Driver
          #基本属性
          url: jdbc:mysql://${config.mysql.host}:${config.mysql.port}/ngtesting-web?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: ngtesting
          password: P2ssw0rd
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 1
          max-active: 20
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.ngtesting.platform.model
  typeHandlersPackage: com.ngtesting.platform.typehandler

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

mail:
  smtp:
    host: smtp.qq.com
    auth: true
    timeout: 50000
    port: 465
    starttls:
    enable: false
    encoding: UTF-8
    username: 3193472405@qq.com
    password: dkwmlkquhjbzdgje

sys:
  name: ngtesting
  work:
    dir: /work/ngtesting-data/
    my-mind-test: /Users/aaron/dev/project
  url:
    login: http://{0}#/login
    resetPassword: http://{0}#/reset-password

---
spring:
  profiles: dev
config:
  mysql:
    host: localhost
    port: 3306

---
spring:
  profiles: prod
config:
  mysql:
    host: localhost
    port: 3306

---
spring:
  profiles: docker
config:
  mysql:
    host: ngtesting-mysql
    port: 3306

---
spring:
  profiles: aliyun-db
config:
  mysql:
    host: 47.99.102.138
    port: 3306
